# Generated by Django 5.0 on 2023-12-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicformapp', '0002_dynamicformdata_name_dynamicformdata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicformdata',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dynamicformdata',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
